// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Users.Database;

#nullable disable

namespace Users.Database.Migrations
{
    [DbContext(typeof(UsersContext))]
    partial class UsersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Users.Domain.User", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("_id"));

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uuid");

                    b.Property<string>("_emailAddress")
                        .HasColumnType("text")
                        .HasColumnName("EmailAddress");

                    b.Property<bool>("_welcomeEmailWasSend")
                        .HasColumnType("boolean")
                        .HasColumnName("WelcomeEmailWasSend");

                    b.HasKey("_id");

                    b.HasAlternateKey("UniqueId");

                    b.ToTable("Users", "users_app");
                });

            modelBuilder.Entity("Users.Domain.User", b =>
                {
                    b.OwnsOne("Users.Domain.AuthCredentials", "_credentials", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("UserId")
                                .HasColumnType("integer");

                            b1.Property<string>("_name")
                                .HasColumnType("text")
                                .HasColumnName("UserName");

                            b1.Property<string>("_password")
                                .HasColumnType("text")
                                .HasColumnName("Password");

                            b1.Property<DateTime?>("_passwordExpirationDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("PasswordExpirationDate");

                            b1.HasKey("Id");

                            b1.HasIndex("UserId")
                                .IsUnique();

                            b1.ToTable("Credentials", "users_app");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("_credentials");
                });
#pragma warning restore 612, 618
        }
    }
}
